version: '3.8'
services:
  app:
    container_name: currencyService
    image: currency-service:1.1
    ports:
      - "8080:8080"
    depends_on:
      - db
      - activemq
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  activemq:
    image: rmohr/activemq:5.14.0-alpine
    restart: always
    environment:
      - ACTIVEMQ_LOGIN=admin
      - ACTIVEMQ_PASSWORD=admin
    ports:
      - '61617:61616'
volumes:
  db:
    driver: local