version: '3.8'
services:
  app:
    container_name: currencyService
    image: springboot-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
      - activeMQueue
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  activeMQueue:
    image: rmohr/activemq:5.15.9-alpine
    restart: always
    environment:
      - ACTIVEMQ_LOGIN=admin
      - ACTIVEMQ_PASSWORD=admin
    ports:
      - '61616:61616'
volumes:
  db:
    driver: local